"""
Enhanced Emission Forecast Training Pipeline

Trains machine learning models to predict weekly carbon emissions using
time series cross-validation and automated model selection.
Features temporal, operational, and categorical (country, industry) data.
"""
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import logging
import warnings
import random
from datetime import datetime
from typing import Dict, List, Tuple
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score, TimeSeriesSplit
import joblib
import matplotlib
matplotlib.use('Agg')  # Headless backend for server environments

# ====================
# CONFIGURATION
# ====================

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)
warnings.filterwarnings('ignore', category=FutureWarning)

# Model hyperparameters
MODEL_CONFIG = {
    'GradientBoosting': {
        'n_estimators': 100,
        'learning_rate': 0.05,
        'max_depth': 5,
        'random_state': 42,
        'verbose': 0
    },
    'RandomForest': {
        'n_estimators': 100,
        'max_depth': 10,
        'random_state': 42,
        'n_jobs': -1,
        'verbose': 0
    },
    'Ridge': {
        'alpha': 1.0,
        'random_state': 42
    }
}

# Training configuration
TRAIN_TEST_SPLIT = 0.8
CV_SPLITS = 5
RANDOM_SEED = 42
TARGET_COLUMN = "total_emissions_tco2e"

# Set random seeds
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

# ====================
# HELPER FUNCTIONS
# ====================


def display_dataframe_to_user(title: str, df: pd.DataFrame, max_rows: int = 10) -> None:
    """Print a DataFrame to the console with formatting.

    Args:
        title: Title to display above the DataFrame
        df: DataFrame to display
        max_rows: Maximum number of rows to show
    """
    print(f"\n=== {title} ===")
    try:
        from tabulate import tabulate
        print(tabulate(df.head(max_rows), headers="keys",
              tablefmt="psql", showindex=False))
    except ImportError:
        print(df.head(max_rows).to_string(index=False))
    print(f"(shape: {df.shape})\n")


def get_season(month: int) -> str:
    """Convert month number to season (Northern Hemisphere).

    Args:
        month: Month number (1-12)

    Returns:
        Season name
    """
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:  # 9, 10, 11
        return 'Autumn'


def extract_facility_type(facility_name: str) -> str:
    """Extract facility type from facility name.

    Args:
        facility_name: Name of the facility

    Returns:
        Facility type category
    """
    type_keywords = ['HQ', 'Plant', 'Factory', 'Office', 'Lab',
                     'Warehouse', 'Center', 'Centre', 'Facility', 'Unit']
    for keyword in type_keywords:
        if keyword in facility_name:
            return 'Plant' if keyword == 'Factory' else keyword
    return 'Other'


def calculate_mape(y_true: np.ndarray, y_pred: np.ndarray, epsilon: float = 1e-10) -> float:
    """Calculate Mean Absolute Percentage Error with numerical stability.

    Args:
        y_true: Actual values
        y_pred: Predicted values
        epsilon: Small constant to avoid division by zero

    Returns:
        MAPE as percentage
    """
    return np.mean(np.abs((y_true - y_pred) / np.clip(y_true, epsilon, None))) * 100


def save_plot(fig: plt.Figure, filename: str, output_dir: str, dpi: int = 150) -> str:
    """Save matplotlib figure to file.

    Args:
        fig: Matplotlib figure to save
        filename: Output filename
        output_dir: Output directory path
        dpi: Resolution in dots per inch

    Returns:
        Full path to saved file
    """
    filepath = os.path.join(output_dir, filename)
    fig.savefig(filepath, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    return filepath


# ====================
# LOAD DATASET
# ====================

logger.info("Loading synthetic dataset...")

# Load the CSV generated by dataset_generator.py
output_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(output_dir, 'ecosphere_synthetic.csv')

if not os.path.exists(csv_path):
    logger.error(f"Dataset not found at {csv_path}")
    logger.info("Please run dataset_generator.py first to generate the dataset")
    raise FileNotFoundError(f"Dataset not found: {csv_path}")

df = pd.read_csv(csv_path)
logger.info(f"Loaded dataset: {df.shape}")

# Convert week_start_date to datetime (weekly data)
if 'week_start_date' in df.columns:
    df['date'] = pd.to_datetime(df['week_start_date'])
    logger.info("Processing weekly aggregated data")
elif 'date' in df.columns:
    df['date'] = pd.to_datetime(df['date'])
    logger.info("Processing daily data")
else:
    raise ValueError(
        "Dataset must have either 'week_start_date' or 'date' column")

# ====================
# FEATURE ENGINEERING
# ====================

logger.info("Starting feature engineering...")

# Extract temporal features
df['month'] = df['date'].dt.month
df['quarter'] = df['date'].dt.quarter
df['week_of_year'] = df['date'].dt.isocalendar().week
df['year'] = df['date'].dt.year
df['season'] = df['month'].apply(get_season)
df['facility_type'] = df['facility_name'].apply(extract_facility_type)

# One-hot encode categorical features including new country and industry_sector
categorical_cols = ['season', 'facility_type', 'country', 'industry_sector']
df_encoded = pd.get_dummies(
    df, columns=categorical_cols,
    prefix=['season', 'fac_type', 'country', 'industry'])

logger.info(f"Feature engineering complete. New shape: {df_encoded.shape}")
logger.info(f"Categorical features encoded: {categorical_cols}")

# Save CSV to backend/ folder (same directory as this script)
output_dir = os.path.dirname(os.path.abspath(__file__))
out_csv = os.path.join(output_dir, 'ecosphere_synthetic.csv')

try:
    df.to_csv(out_csv, index=False)
    logger.info(f"Saved synthetic dataset to: {out_csv}")
except Exception as e:
    logger.error(f"Failed to save CSV: {e}")
    raise

# ====================
# ENHANCED TRAINING PIPELINE
# ====================

logger.info("Starting enhanced training pipeline...")

# Define base numerical features (weekly data)
base_features = [
    "electricity_consumption_kwh",  # Weekly total
    "renewable_energy_kwh",  # Weekly total
    "fuel_consumed_liters",  # Weekly total
    "distance_travelled_km",  # Weekly total
    "spend_amount_inr",  # Weekly total
    "temperature_celsius",  # Weekly average
    "humidity_percent",  # Weekly average
    "occupancy_rate_percent",  # Weekly average
    "product_output_units",  # Weekly total
    "machine_runtime_hours",  # Weekly total
    "equipment_power_rating_kw",
    "employee_count",
    # Temporal features for weekly data
    "month",
    "quarter",
    "week_of_year",
    "year"
]

# Add one-hot encoded features
season_cols = [col for col in df_encoded.columns if col.startswith('season_')]
facility_cols = [
    col for col in df_encoded.columns if col.startswith('fac_type_')]
country_cols = [
    col for col in df_encoded.columns if col.startswith('country_')]
industry_cols = [
    col for col in df_encoded.columns if col.startswith('industry_')]

# Combine all features
features = base_features + season_cols + \
    facility_cols + country_cols + industry_cols

logger.info(f"Total features: {len(features)} ({len(base_features)} numerical + "
            f"{len(season_cols)} season + {len(facility_cols)} facility + "
            f"{len(country_cols)} country + {len(industry_cols)} industry)")

target = "total_emissions_tco2e"

# Data cleaning and validation
df_encoded = df_encoded[df_encoded[target].notna()].copy()
df_encoded.sort_values('date', inplace=True)
df_encoded.reset_index(drop=True, inplace=True)

# Ensure all features exist
for col in features:
    if col not in df_encoded.columns:
        df_encoded[col] = 0.0
        logger.warning(f"Feature '{col}' not found, filled with 0.0")

logger.info(f"Dataset shape: {df_encoded.shape}, Features: {len(features)}")

# Extract features and target
X = df_encoded[features].copy()
y = df_encoded[target].copy().values

# Preprocessing pipeline with error handling
try:
    imputer = SimpleImputer(strategy='median')
    X_imputed = imputer.fit_transform(X)
    logger.info("Data imputation completed")

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)
    logger.info("Feature scaling completed")
except Exception as e:
    logger.error(f"Preprocessing failed: {e}")
    raise

# Temporal train/test split (respects time ordering)
split_idx = int(len(df) * TRAIN_TEST_SPLIT)
X_train = X_scaled[:split_idx]
X_test = X_scaled[split_idx:]
y_train = y[:split_idx]
y_test = y[split_idx:]

logger.info(f"Train size: {len(X_train):,}, Test size: {len(X_test):,}")

# ====================
# MODEL COMPARISON
# ====================

logger.info("Training multiple models for comparison...")

# Initialize models with config
models = {
    'GradientBoosting': GradientBoostingRegressor(**MODEL_CONFIG['GradientBoosting']),
    'RandomForest': RandomForestRegressor(**MODEL_CONFIG['RandomForest']),
    'Ridge': Ridge(**MODEL_CONFIG['Ridge'])
}

# Cross-validation with TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=CV_SPLITS)
cv_results = {}

for name, model in models.items():
    try:
        # Time series cross-validation
        cv_scores = cross_val_score(
            model, X_train, y_train,
            cv=tscv,
            scoring='r2',
            n_jobs=-1
        )
        cv_results[name] = {
            'mean_r2': cv_scores.mean(),
            'std_r2': cv_scores.std()
        }
        logger.info(
            f"{name} - CV R²: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")
    except Exception as e:
        logger.error(f"Cross-validation failed for {name}: {e}")

# Select best model based on CV
best_model_name = max(cv_results, key=lambda k: cv_results[k]['mean_r2'])
best_model = models[best_model_name]
logger.info(f"Best model selected: {best_model_name}")

# Train best model on full training set
try:
    best_model.fit(X_train, y_train)
    logger.info(f"{best_model_name} training completed")
except Exception as e:
    logger.error(f"Model training failed: {e}")
    raise

# ====================
# MODEL EVALUATION
# ====================

y_pred = best_model.predict(X_test)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
mape = calculate_mape(y_test, y_pred)

logger.info(
    f"Test Results - MAE: {mae:.4f}, RMSE: {rmse:.4f}, R²: {r2:.4f}, MAPE: {mape:.2f}%")

# Prediction intervals (approximate using residuals)
residuals = y_test - y_pred
residual_std = np.std(residuals)
pred_interval_95 = 1.96 * residual_std

# ====================
# SAVE MODEL & ARTIFACTS
# ====================

try:
    out_model_path = os.path.join(output_dir, 'emission_forecast_model.pkl')
    os.makedirs(os.path.dirname(out_model_path) or '.', exist_ok=True)

    model_artifact = {
        'model': best_model,
        'model_name': best_model_name,
        'scaler': scaler,
        'imputer': imputer,
        'features': features,
        'cv_results': cv_results,
        'test_metrics': {
            'mae': mae,
            'rmse': rmse,
            'r2': r2,
            'mape': mape
        },
        'pred_interval_95': pred_interval_95,
        'training_date': datetime.now().isoformat()
    }

    joblib.dump(model_artifact, out_model_path)
    logger.info(f"Model saved to: {out_model_path}")
except Exception as e:
    logger.error(f"Failed to save model: {e}")
    raise

# ====================
# DISPLAY RESULTS
# ====================

# Compare all models
comparison_df = pd.DataFrame([
    {
        'model': name,
        'CV_R2_mean': cv_results[name]['mean_r2'],
        'CV_R2_std': cv_results[name]['std_r2']
    }
    for name in cv_results.keys()
])
display_dataframe_to_user("Model Comparison (Cross-Validation)", comparison_df)

# Best model metrics
metrics_df = pd.DataFrame([{
    'model': best_model_name,
    'MAE': round(mae, 4),
    'RMSE': round(rmse, 4),
    'R2': round(r2, 6),
    'MAPE_%': round(mape, 2),
    'Pred_Interval_95%': f"±{pred_interval_95:.4f}"
}])
display_dataframe_to_user("Test Set Evaluation", metrics_df)

# Sample predictions with confidence intervals
sample_idx = random.sample(range(len(y_test)), k=min(10, len(y_test)))
sample_df = df_encoded.iloc[split_idx:].iloc[sample_idx][[
    'date', 'facility_name']].copy().reset_index(drop=True)
sample_df['actual_tco2e'] = y_test[sample_idx]
sample_df['predicted_tco2e'] = np.round(y_pred[sample_idx], 4)
sample_df['error'] = np.round(y_test[sample_idx] - y_pred[sample_idx], 4)
sample_df['error_%'] = np.round(
    100 * sample_df['error'] / np.clip(sample_df['actual_tco2e'], 1e-10, None), 2)
display_dataframe_to_user("Sample Predictions with Errors", sample_df)

# ====================
# VISUALIZATION
# ====================

try:
    # Plot 1: Actual vs Predicted with confidence interval
    plt.figure(figsize=(12, 5))
    plt.plot(y_test, label='Actual', alpha=0.7, linewidth=2)
    plt.plot(y_pred, label='Predicted', alpha=0.7, linewidth=2)
    plt.fill_between(
        range(len(y_pred)),
        y_pred - pred_interval_95,
        y_pred + pred_interval_95,
        alpha=0.2,
        label='95% Prediction Interval'
    )
    plt.title(f'Actual vs Predicted - {best_model_name} (R²={r2:.4f})')
    plt.xlabel('Test sample index')
    plt.ylabel('Total emissions (tCO2e)')
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt_path1 = os.path.join(output_dir, 'actual_vs_predicted.png')
    plt.savefig(plt_path1, dpi=150)
    plt.close()
    logger.info(f"Saved plot: {plt_path1}")

    # Plot 2: Feature importance (if available)
    if hasattr(best_model, 'feature_importances_'):
        imp = best_model.feature_importances_
        imp_norm = imp / imp.sum() if imp.sum() > 0 else imp

        plt.figure(figsize=(10, 6))
        indices = np.argsort(imp_norm)[::-1]
        colors = plt.cm.viridis(np.linspace(0, 1, len(features)))
        plt.bar(range(len(features)), imp_norm[indices], color=colors)
        plt.xticks(range(len(features)), [features[i] for i in indices],
                   rotation=45, ha='right')
        plt.title(f'Feature Importance - {best_model_name}')
        plt.ylabel('Normalized Importance')
        plt.grid(axis='y', alpha=0.3)
        plt.tight_layout()
        plt_path2 = os.path.join(output_dir, 'feature_importance.png')
        plt.savefig(plt_path2, dpi=150)
        plt.close()
        logger.info(f"Saved plot: {plt_path2}")
    else:
        logger.warning(f"{best_model_name} does not have feature_importances_")
        plt_path2 = None

    # Plot 3: Residuals distribution
    plt.figure(figsize=(10, 5))
    plt.hist(residuals, bins=30, edgecolor='black', alpha=0.7)
    plt.axvline(0, color='red', linestyle='--',
                linewidth=2, label='Zero error')
    plt.title('Residuals Distribution')
    plt.xlabel('Residual (Actual - Predicted)')
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt_path3 = os.path.join(output_dir, 'residuals_distribution.png')
    plt.savefig(plt_path3, dpi=150)
    plt.close()
    logger.info(f"Saved plot: {plt_path3}")

except Exception as e:
    logger.error(f"Visualization failed: {e}")

# ====================
# SUMMARY
# ====================

print(f"\n{'='*60}")
print(f"{'TRAINING COMPLETE':^60}")
print(f"{'='*60}")
print(f"Saved synthetic CSV to: {out_csv}")
print(f"Model saved to: {out_model_path}")
print(f"Actual vs Predicted plot: {plt_path1}")
if plt_path2:
    print(f"Feature importance plot: {plt_path2}")
print(f"Residuals distribution plot: {plt_path3}")
print(f"{'='*60}\n")
